// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: create_revision.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRevision = `-- name: CreateRevision :one
INSERT INTO recipe_revisions (
  recipe_id,
  parent_id,
  recipe_description,
  change_comment,
  title,
  photo,
  publish_date
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING
  id,
  recipe_id,
  parent_id,
  recipe_description,
  change_comment,
  title,
  publish_date,
  photo
`

type CreateRevisionParams struct {
	RecipeID          pgtype.UUID
	ParentID          pgtype.UUID
	RecipeDescription pgtype.Text
	ChangeComment     pgtype.Text
	Title             string
	Photo             pgtype.Text
	PublishDate       pgtype.Timestamp
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) (RecipeRevision, error) {
	row := q.db.QueryRow(ctx, createRevision,
		arg.RecipeID,
		arg.ParentID,
		arg.RecipeDescription,
		arg.ChangeComment,
		arg.Title,
		arg.Photo,
		arg.PublishDate,
	)
	var i RecipeRevision
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.ParentID,
		&i.RecipeDescription,
		&i.ChangeComment,
		&i.Title,
		&i.PublishDate,
		&i.Photo,
	)
	return i, err
}
