// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: create_recipe_ingredient.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecipeIngredient = `-- name: CreateRecipeIngredient :one
INSERT INTO
  recipe_ingredients (
    revision_id,
    ingredient_id,
    measurement_unit_id,
    quantity,
    comment
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  recipe_ingredients.id,
  recipe_ingredients.revision_id,
  recipe_ingredients.ingredient_id,
  recipe_ingredients.quantity,
  recipe_ingredients.measurement_unit_id,
  recipe_ingredients.comment
`

type CreateRecipeIngredientParams struct {
	RevisionID        pgtype.UUID
	IngredientID      int64
	MeasurementUnitID int64
	Quantity          float32
	Comment           pgtype.Text
}

func (q *Queries) CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) (RecipeIngredient, error) {
	row := q.db.QueryRow(ctx, createRecipeIngredient,
		arg.RevisionID,
		arg.IngredientID,
		arg.MeasurementUnitID,
		arg.Quantity,
		arg.Comment,
	)
	var i RecipeIngredient
	err := row.Scan(
		&i.ID,
		&i.RevisionID,
		&i.IngredientID,
		&i.Quantity,
		&i.MeasurementUnitID,
		&i.Comment,
	)
	return i, err
}
