// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: create_recipe_step.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecipeStep = `-- name: CreateRecipeStep :one
INSERT INTO
  recipe_steps (
    revision_id,
    content,
    index,
    photo
  )
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING
  id,
  revision_id,
  content,
  index,
  photo
`

type CreateRecipeStepParams struct {
	RevisionID pgtype.UUID
	Content    string
	Index      int32
	Photo      pgtype.Text
}

func (q *Queries) CreateRecipeStep(ctx context.Context, arg CreateRecipeStepParams) (RecipeStep, error) {
	row := q.db.QueryRow(ctx, createRecipeStep,
		arg.RevisionID,
		arg.Content,
		arg.Index,
		arg.Photo,
	)
	var i RecipeStep
	err := row.Scan(
		&i.ID,
		&i.RevisionID,
		&i.Content,
		&i.Index,
		&i.Photo,
	)
	return i, err
}
