// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete_magic_link.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMagicLinkById = `-- name: DeleteMagicLinkById :exec
DELETE FROM
  magic_links
WHERE magic_links.id = $1
`

func (q *Queries) DeleteMagicLinkById(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMagicLinkById, id)
	return err
}
