// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_recipe_revision_rating_average.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecipeRevisionRatingAverage = `-- name: GetRecipeRevisionRatingAverage :one
SELECT AVG(star_value) AS average
FROM ratings
WHERE revision_id = $1::uuid
`

func (q *Queries) GetRecipeRevisionRatingAverage(ctx context.Context, revisionID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getRecipeRevisionRatingAverage, revisionID)
	var average pgtype.Numeric
	err := row.Scan(&average)
	return average, err
}
