// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_magic_link.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMagicLink = `-- name: GetMagicLink :one
SELECT
  magic_links.id,
  magic_links.token,
  magic_links.user_id,
  magic_links.expiry
FROM
  magic_links
WHERE
  magic_links.id = $1 AND magic_links.token = $2
`

type GetMagicLinkParams struct {
	ID    pgtype.UUID
	Token pgtype.UUID
}

type GetMagicLinkRow struct {
	ID     pgtype.UUID
	Token  pgtype.UUID
	UserID pgtype.UUID
	Expiry pgtype.Timestamp
}

func (q *Queries) GetMagicLink(ctx context.Context, arg GetMagicLinkParams) (GetMagicLinkRow, error) {
	row := q.db.QueryRow(ctx, getMagicLink, arg.ID, arg.Token)
	var i GetMagicLinkRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.Expiry,
	)
	return i, err
}
