// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_user_and_session_by_session_id.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserBySessionId = `-- name: GetUserBySessionId :one
SELECT
  users.id, users.display_name, users.email, users.join_date, users.updated_at, users.photo,
  sessions.id, sessions.user_id, sessions.expiry
FROM
  sessions
JOIN
  users ON users.id = sessions.user_id
WHERE
  sessions.id = $1
LIMIT 1
`

type GetUserBySessionIdRow struct {
	User    User
	Session Session
}

func (q *Queries) GetUserBySessionId(ctx context.Context, sessionID pgtype.UUID) (GetUserBySessionIdRow, error) {
	row := q.db.QueryRow(ctx, getUserBySessionId, sessionID)
	var i GetUserBySessionIdRow
	err := row.Scan(
		&i.User.ID,
		&i.User.DisplayName,
		&i.User.Email,
		&i.User.JoinDate,
		&i.User.UpdatedAt,
		&i.User.Photo,
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.Expiry,
	)
	return i, err
}
