// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_latest_recipe_revision_by_recipe_id.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestRecipeRevisionByRecipeId = `-- name: GetLatestRecipeRevisionByRecipeId :one
SELECT
  id,
  recipe_id,
  parent_id,
  recipe_description,
  change_comment,
  title,
  publish_date,
  photo
FROM
  recipe_revisions
WHERE
  recipe_id = $1
ORDER BY
  publish_date DESC
LIMIT 1
`

func (q *Queries) GetLatestRecipeRevisionByRecipeId(ctx context.Context, recipeID pgtype.UUID) (RecipeRevision, error) {
	row := q.db.QueryRow(ctx, getLatestRecipeRevisionByRecipeId, recipeID)
	var i RecipeRevision
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.ParentID,
		&i.RecipeDescription,
		&i.ChangeComment,
		&i.Title,
		&i.PublishDate,
		&i.Photo,
	)
	return i, err
}
