// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_measurement_unit_by_id.sql

package db

import (
	"context"
)

const getMeasurementUnitById = `-- name: GetMeasurementUnitById :one
SELECT
  measurement_units.id,
  measurement_units.name,
  measurement_units.description
FROM
  measurement_units
WHERE
  measurement_units.id = $1
LIMIT 1
`

func (q *Queries) GetMeasurementUnitById(ctx context.Context, id int64) (MeasurementUnit, error) {
	row := q.db.QueryRow(ctx, getMeasurementUnitById, id)
	var i MeasurementUnit
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
