// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_user_by_display_name.sql

package db

import (
	"context"
)

const getUserByDisplayName = `-- name: GetUserByDisplayName :one
SELECT users.id, users.display_name, users.email, users.join_date, users.updated_at, users.photo FROM users WHERE users.display_name = $1 LIMIT 1
`

func (q *Queries) GetUserByDisplayName(ctx context.Context, displayName string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDisplayName, displayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.JoinDate,
		&i.UpdatedAt,
		&i.Photo,
	)
	return i, err
}
