// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: has_user_rated_revision.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hasUserRatedRevision = `-- name: HasUserRatedRevision :one
SELECT EXISTS(
    SELECT star_value
    FROM ratings
    WHERE
        revision_id = $1::uuid
        AND
        user_id = $2::uuid
)
`

type HasUserRatedRevisionParams struct {
	RevisionID pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) HasUserRatedRevision(ctx context.Context, arg HasUserRatedRevisionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserRatedRevision, arg.RevisionID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
