// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ingredient.sql

package db

import (
	"context"
)

const getIngredientFromRecipeIngredientId = `-- name: GetIngredientFromRecipeIngredientId :one
SELECT
  ingredients.id,
  ingredients.name,
  ingredients.description
FROM
  recipe_ingredients
JOIN
  ingredients ON recipe_ingredients.ingredient = ingredients.id
WHERE
  recipe_ingredients.id = $1
LIMIT 1
`

func (q *Queries) GetIngredientFromRecipeIngredientId(ctx context.Context, id int64) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientFromRecipeIngredientId, id)
	var i Ingredient
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
