// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: list_steps_by_recipe_revision_id.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listStepsByRecipeRevisionID = `-- name: ListStepsByRecipeRevisionID :many
SELECT
  recipe_steps.id,
  recipe_steps.revision_id,
  recipe_steps.content,
  recipe_steps.index,
  recipe_steps.photo
FROM
  recipe_revisions
JOIN
  recipe_steps ON recipe_revisions.id = recipe_steps.revision_id
WHERE
  recipe_revisions.id = $1
ORDER BY
  recipe_steps.index
`

func (q *Queries) ListStepsByRecipeRevisionID(ctx context.Context, revisionID pgtype.UUID) ([]RecipeStep, error) {
	rows, err := q.db.Query(ctx, listStepsByRecipeRevisionID, revisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeStep
	for rows.Next() {
		var i RecipeStep
		if err := rows.Scan(
			&i.ID,
			&i.RevisionID,
			&i.Content,
			&i.Index,
			&i.Photo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
