// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ingredient struct {
	ID          int64
	Name        string
	Description pgtype.Text
}

type IngredientTag struct {
	ID         int64
	Ingredient int64
	Tag        int64
}

type LinkedRecipe struct {
	FromRecipeID int64
	ToRecipeID   int64
}

type MagicLink struct {
	ID     int64
	UserID int64
	Token  string
	Expiry pgtype.Timestamp
}

type MeasurementUnit struct {
	ID          int64
	Name        string
	Description pgtype.Text
}

type MeasurementUnitsTag struct {
	ID          int64
	Measurement int64
	Tag         int64
}

type Rating struct {
	ID         int64
	RevisionID int64
	UserID     int64
	StarValue  pgtype.Int2
}

type Recipe struct {
	ID                 int64
	AuthorID           int64
	Slug               string
	Private            bool
	InitialPublishDate pgtype.Timestamp
	ForkedFrom         pgtype.Int8
	FeaturedRevision   pgtype.Int8
}

type RecipeIngredient struct {
	ID         int64
	RevisionID int64
	Ingredient string
	Quantity   float32
	Unit       string
	Comment    pgtype.Text
}

type RecipeRevision struct {
	ID                int64
	RecipeID          int64
	ParentID          pgtype.Int8
	RecipeDescription pgtype.Text
	ChangeComment     pgtype.Text
	Title             string
	PublishDate       pgtype.Timestamp
}

type RecipeStep struct {
	ID         int64
	RevisionID int64
	Content    string
	Index      int32
}

type Session struct {
	ID     int64
	UserID int64
	Expiry pgtype.Timestamp
}

type Tag struct {
	ID            int64
	Name          string
	Description   pgtype.Text
	UserGenerated bool
}

type User struct {
	ID          int64
	DisplayName string
	Email       string
	JoinDate    pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
