// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ingredient struct {
	ID          int64
	Name        string
	Description pgtype.Text
}

type IngredientTag struct {
	IngredientID int64
	TagID        int64
}

type MagicLink struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Token  pgtype.UUID
	Expiry pgtype.Timestamp
}

type MeasurementUnit struct {
	ID          int64
	Name        string
	Description pgtype.Text
}

type MeasurementUnitsTag struct {
	MeasurementUnitID int64
	TagID             int64
}

type Rating struct {
	RevisionID pgtype.UUID
	UserID     pgtype.UUID
	StarValue  pgtype.Int2
}

type Recipe struct {
	ID                 pgtype.UUID
	AuthorID           pgtype.UUID
	Slug               string
	Private            bool
	InitialPublishDate pgtype.Timestamp
	ForkedFrom         pgtype.UUID
	FeaturedRevision   pgtype.UUID
}

type RecipeIngredient struct {
	ID                int64
	RevisionID        pgtype.UUID
	IngredientID      int64
	Quantity          float32
	MeasurementUnitID int64
	Comment           pgtype.Text
}

type RecipeRevision struct {
	ID                pgtype.UUID
	RecipeID          pgtype.UUID
	ParentID          pgtype.UUID
	RecipeDescription pgtype.Text
	ChangeComment     pgtype.Text
	Title             string
	PublishDate       pgtype.Timestamp
	Photo             pgtype.Text
}

type RecipeStep struct {
	ID         int64
	RevisionID pgtype.UUID
	Content    string
	Index      int32
	Photo      pgtype.Text
}

type Session struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Expiry pgtype.Timestamp
}

type Tag struct {
	ID            int64
	Name          string
	Description   pgtype.Text
	UserGenerated bool
}

type User struct {
	ID          pgtype.UUID
	DisplayName string
	Email       string
	JoinDate    pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	Photo       pgtype.Text
}
