// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (CreateMagicLinkRow, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) (RecipeIngredient, error)
	CreateRecipeStep(ctx context.Context, arg CreateRecipeStepParams) (RecipeStep, error)
	CreateRevision(ctx context.Context, arg CreateRevisionParams) (RecipeRevision, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMagicLinkById(ctx context.Context, id pgtype.UUID) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	GetIngredientById(ctx context.Context, id int64) (Ingredient, error)
	GetLatestRecipeRevisionByRecipeId(ctx context.Context, recipeID pgtype.UUID) (RecipeRevision, error)
	GetMagicLink(ctx context.Context, arg GetMagicLinkParams) (GetMagicLinkRow, error)
	GetMeasurementUnitById(ctx context.Context, id int64) (MeasurementUnit, error)
	GetRecipeById(ctx context.Context, id pgtype.UUID) (Recipe, error)
	GetRecipeBySlug(ctx context.Context, arg GetRecipeBySlugParams) (Recipe, error)
	GetRecipeRevisionById(ctx context.Context, id pgtype.UUID) (RecipeRevision, error)
	GetRecipeRevisionRatingAverage(ctx context.Context, revisionID pgtype.UUID) (pgtype.Numeric, error)
	GetUserByDisplayName(ctx context.Context, displayName string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserBySessionId(ctx context.Context, id pgtype.UUID) (GetUserBySessionIdRow, error)
	HasUserRatedRevision(ctx context.Context, arg HasUserRatedRevisionParams) (bool, error)
	ListIngredientsByRecipeRevisionID(ctx context.Context, id pgtype.UUID) ([]RecipeIngredient, error)
	ListRecipes(ctx context.Context, arg ListRecipesParams) ([]Recipe, error)
	//Used when there is not a featured recipe
	//and recipe_id = 'ae1f8b91-3659-4f7e-b484-dd54e7f3d2b3'
	//Used when there is a featured recipe
	ListRecipesWithQuery(ctx context.Context, arg ListRecipesWithQueryParams) ([]ListRecipesWithQueryRow, error)
	ListRevisions(ctx context.Context, arg ListRevisionsParams) ([]RecipeRevision, error)
	ListStepsByRecipeRevisionID(ctx context.Context, id pgtype.UUID) ([]RecipeStep, error)
	SeedRecipe(ctx context.Context, arg SeedRecipeParams) (Recipe, error)
	SeedRevision(ctx context.Context, arg SeedRevisionParams) (RecipeRevision, error)
	SeedUser(ctx context.Context, arg SeedUserParams) (User, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertIngredient(ctx context.Context, name string) (UpsertIngredientRow, error)
	UpsertMeasurementUnit(ctx context.Context, name string) (UpsertMeasurementUnitRow, error)
	UpsertRating(ctx context.Context, arg UpsertRatingParams) (Rating, error)
}

var _ Querier = (*Queries)(nil)
