// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: seed_user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const seedUser = `-- name: SeedUser :one
INSERT INTO
  users (
    email,
    display_name,
    join_date
  )
VALUES (
  $1,
  $2,
  $3
)
RETURNING
  users.id,
  users.display_name,
  users.email,
  users.join_date,
  users.updated_at,
  users.photo
`

type SeedUserParams struct {
	Email       string
	DisplayName string
	JoinDate    pgtype.Timestamp
}

func (q *Queries) SeedUser(ctx context.Context, arg SeedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, seedUser, arg.Email, arg.DisplayName, arg.JoinDate)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.JoinDate,
		&i.UpdatedAt,
		&i.Photo,
	)
	return i, err
}
