// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: seed_recipe.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const seedRecipe = `-- name: SeedRecipe :one
INSERT INTO recipes (
  author_id,
  forked_from,
  slug,
  private,
  initial_publish_date
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
) RETURNING
  id,
  author_id,
  slug,
  private,
  initial_publish_date,
  forked_from,
  featured_revision
`

type SeedRecipeParams struct {
	AuthorID           pgtype.UUID
	ForkedFrom         pgtype.UUID
	Slug               string
	Private            bool
	InitialPublishDate pgtype.Timestamp
}

func (q *Queries) SeedRecipe(ctx context.Context, arg SeedRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, seedRecipe,
		arg.AuthorID,
		arg.ForkedFrom,
		arg.Slug,
		arg.Private,
		arg.InitialPublishDate,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.Private,
		&i.InitialPublishDate,
		&i.ForkedFrom,
		&i.FeaturedRevision,
	)
	return i, err
}
