// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_recipe.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes
SET
  slug = coalesce($1, slug),
  private = coalesce($2, private),
  featured_revision = coalesce($3, featured_revision)
WHERE id = $4
RETURNING
  id,
  author_id,
  slug,
  private,
  initial_publish_date,
  forked_from,
  featured_revision
`

type UpdateRecipeParams struct {
	Slug             string
	Private          bool
	FeaturedRevision pgtype.UUID
	ID               pgtype.UUID
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, updateRecipe,
		arg.Slug,
		arg.Private,
		arg.FeaturedRevision,
		arg.ID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.Private,
		&i.InitialPublishDate,
		&i.ForkedFrom,
		&i.FeaturedRevision,
	)
	return i, err
}
