// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = $2, email = $3, photo = $4
WHERE id = $1
RETURNING
  id,
  display_name,
  email,
  join_date,
  updated_at,
  photo
`

type UpdateUserParams struct {
	ID          pgtype.UUID
	DisplayName string
	Email       string
	Photo       pgtype.Text
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.Photo,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.JoinDate,
		&i.UpdatedAt,
		&i.Photo,
	)
	return i, err
}
