// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: upsert_ingredient.sql

package db

import (
	"context"
)

const upsertIngredient = `-- name: UpsertIngredient :one
WITH upsert AS (
  INSERT INTO
    ingredients (
      name
    )
  VALUES (
    $1
  )
  ON CONFLICT (name)
  DO NOTHING
  RETURNING
    ingredients.id,
    ingredients.name
)
SELECT
  upsert.id,
	upsert.name
FROM
  upsert
UNION
SELECT
    ingredients.id,
    ingredients.name
FROM
  ingredients
WHERE
  ingredients.name = $1
`

type UpsertIngredientRow struct {
	ID   int64
	Name string
}

func (q *Queries) UpsertIngredient(ctx context.Context, name string) (UpsertIngredientRow, error) {
	row := q.db.QueryRow(ctx, upsertIngredient, name)
	var i UpsertIngredientRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
