// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
	username,
	email
) VALUES (
	$1,
	$2
)
RETURNING join_date, username, email, id
`

type CreateUserParams struct {
	Username string
	Email    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.JoinDate,
		&i.Username,
		&i.Email,
		&i.ID,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT join_date, username, email, id FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.JoinDate,
		&i.Username,
		&i.Email,
		&i.ID,
	)
	return i, err
}
