package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"forkd/graph/model"
)

// Revision is the resolver for the revision field.
func (r *recipeIngredientResolver) Revision(ctx context.Context, obj *model.RecipeIngredient) (*model.RecipeRevision, error) {
	return r.RecipeService.GetRecipeRevisionById(ctx, obj.Revision.ID)
}

// Unit is the resolver for the unit field.
func (r *recipeIngredientResolver) Unit(ctx context.Context, obj *model.RecipeIngredient) (*model.MeasurementUnit, error) {
	return r.RecipeService.GetMeasurementUnitById(ctx, int64(obj.Unit.ID))
}

// Ingredient is the resolver for the ingredient field.
func (r *recipeIngredientResolver) Ingredient(ctx context.Context, obj *model.RecipeIngredient) (*model.Ingredient, error) {
	return r.RecipeService.GetIngredientById(ctx, int64(obj.Ingredient.ID))
}

// RecipeIngredient returns RecipeIngredientResolver implementation.
func (r *Resolver) RecipeIngredient() RecipeIngredientResolver { return &recipeIngredientResolver{r} }

type recipeIngredientResolver struct{ *Resolver }
