// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PaginatedResult interface {
	IsPaginatedResult()
	GetPagination() *PaginationInfo
}

type Ingredient struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type MeasurementUnit struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

type PaginatedComments struct {
	Items      []*RecipeComment `json:"items"`
	Pagination *PaginationInfo  `json:"pagination"`
}

func (PaginatedComments) IsPaginatedResult()                  {}
func (this PaginatedComments) GetPagination() *PaginationInfo { return this.Pagination }

type PaginatedRecipeRevisions struct {
	Items      []*RecipeRevision `json:"items"`
	Pagination *PaginationInfo   `json:"pagination"`
}

func (PaginatedRecipeRevisions) IsPaginatedResult()                  {}
func (this PaginatedRecipeRevisions) GetPagination() *PaginationInfo { return this.Pagination }

type PaginatedRecipes struct {
	Items      []*Recipe       `json:"items"`
	Pagination *PaginationInfo `json:"pagination"`
}

func (PaginatedRecipes) IsPaginatedResult()                  {}
func (this PaginatedRecipes) GetPagination() *PaginationInfo { return this.Pagination }

type PaginationInfo struct {
	Count      int     `json:"count"`
	NextCursor *string `json:"nextCursor,omitempty"`
	PrevCursor *string `json:"prevCursor,omitempty"`
}

type Query struct {
}

type Recipe struct {
	InitialPublishDate string                    `json:"initialPublishDate"`
	Author             *User                     `json:"author"`
	Slug               string                    `json:"slug"`
	ForkedFrom         *int                      `json:"forkedFrom,omitempty"`
	ID                 string                    `json:"id"`
	Description        string                    `json:"description"`
	Revisions          *PaginatedRecipeRevisions `json:"revisions"`
}

type RecipeComment struct {
	Revision *RecipeRevision `json:"revision"`
	PostDate string          `json:"postDate"`
	Recipe   *Recipe         `json:"recipe"`
	Author   *User           `json:"author"`
	Content  string          `json:"content"`
}

type RecipeIngredient struct {
	Revision   *RecipeRevision  `json:"revision"`
	Unit       *MeasurementUnit `json:"unit"`
	Ingredient *Ingredient      `json:"ingredient"`
	Quantity   float64          `json:"quantity"`
	ID         string           `json:"id"`
	Comment    *string          `json:"comment,omitempty"`
}

type RecipeQuery struct {
	ByID   *Recipe           `json:"byId,omitempty"`
	BySlug *Recipe           `json:"bySlug,omitempty"`
	List   *PaginatedRecipes `json:"list"`
}

type RecipeRevision struct {
	ID          string              `json:"id"`
	Description *string             `json:"description,omitempty"`
	PublishDate string              `json:"publishDate"`
	Ingredients []*RecipeIngredient `json:"ingredients"`
	Steps       []*RecipeStep       `json:"steps"`
}

type RecipeStep struct {
	ID       string          `json:"id"`
	Revision *RecipeRevision `json:"revision"`
	Content  string          `json:"content"`
	Index    int             `json:"index"`
}

type Tag struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

type User struct {
	JoinDate string             `json:"joinDate"`
	ID       string             `json:"id"`
	Email    string             `json:"email"`
	Username string             `json:"username"`
	Recipes  *PaginatedRecipes  `json:"recipes"`
	Comments *PaginatedComments `json:"comments"`
}

type UserQuery struct {
	ByID    *User `json:"byId,omitempty"`
	BySlug  *User `json:"bySlug,omitempty"`
	ByEmail *User `json:"byEmail,omitempty"`
}
