query ListRecipes {
  recipe {
    list {
      items {
        slug
        id
        author {
          displayName
        }
        featuredRevision {
          recipeDescription
          publishDate
          rating
          title
        }
      }
    }
  }
}
