// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ingredient struct {
	Name        string
	Description pgtype.Text
}

type IngredientTag struct {
	Tag        string
	Ingredient string
}

type LinkedRecipe struct {
	FromRecipeID int64
	ToRecipeID   int64
}

type MeasurementUnit struct {
	Description pgtype.Text
	Name        string
}

type MeasurementUnitsTag struct {
	Measurement string
	Tag         string
}

type Recipe struct {
	Description        pgtype.Text
	ForkedFrom         pgtype.Int8
	AuthorID           int64
	InitialPublishDate pgtype.Timestamp
	ID                 int64
	Slug               string
}

type RecipeComment struct {
	ID       int64
	RecipeID int64
	AuthorID int64
	Content  string
	PostDate pgtype.Timestamp
}

type RecipeIngredient struct {
	Comment    pgtype.Text
	RevisionID int64
	Ingredient string
	Quantity   float32
	Unit       string
	ID         int64
}

type RecipeRevision struct {
	PublishDate pgtype.Timestamp
	RecipeID    int64
	ParentID    int64
	ChildID     pgtype.Int8
	Description pgtype.Text
	ID          int64
}

type RecipeStep struct {
	Content    string
	RevisionID int64
	ID         int64
	Index      int32
}

type SchemaMigration struct {
	ID string
}

type Tag struct {
	Name        string
	Description pgtype.Text
}

type User struct {
	JoinDate pgtype.Timestamp
	Username string
	Email    string
	ID       int64
}
