// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package data

import (
	"context"
)

const getUserById = `-- name: GetUserById :one
SELECT join_date, username, email, id FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.JoinDate,
		&i.Username,
		&i.Email,
		&i.ID,
	)
	return i, err
}
