name: Go Code Checks

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  go-check:
    name: Go Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "api/go.mod"
          cache-dependency-path: "api/go.sum"
      - name: Check gofmt
        run: gofmt -e -l . | tee /dev/tty | wc -l | xargs -I % test % -lt 1
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v1.63.4
          working-directory: api
