name: SQL Code Checks

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  sql-check:
    name: SQL Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install SQLFluff
        run: pip install sqlfluff
      - name: Run SQLFluff
        run: sqlfluff lint db/**/*.sql --dialect postgres
